### ISSUE TITLE
connect ECONNREFUSED in container logs, eventhough ES up

### ISSUE THREAD

**Issue by Analect** [bobrik/docker-kibana4#1]
@bobrik 
I wanted to use your container to explore kibana. Hope that's ok.

docker run --name kibana4 -d -p 127.0.0.1:5601:5601 -e KIBANA_ES_URL=localhost:9200  bobrik/kibana4
However, it's not visible at localhost:5601 and the logs give these errors. Elasticsearch is up on port 9200. Does there need to be a pre-existing kibana-int index in there for the container to work?

Thanks,
Colum

me@ubuntu-1404:~/Development/Tools/Eolas/aws$ docker logs kibana4
{"@timestamp":"2015-03-05T17:33:51.818Z","level":"error","node_env":"production","error":"Request error, retrying -- connect ECONNREFUSED"}
{"@timestamp":"2015-03-05T17:33:51.822Z","level":"warn","message":"Unable to revive connection: http://localhost:9200/","node_env":"production"}
{"@timestamp":"2015-03-05T17:33:51.823Z","level":"warn","message":"No living connections","node_env":"production"}

**Comment by bobrik** [comment]
Your container has different `localhost` than your host. If your elasticsearch only listens on `localhost`, you should probably use `--het host` when you run kibana container. If it listens other address, pass it instead of `localhost:9200`.

There's no need to have pre-existing kibana index to run kibana.

Let me know if that helps.

**Comment by Analect** [comment]
@bobrik 
Sorry haven't responded to this before now.
The following worked, with 172.17.0.190 being the elasticsearch container IP. Note that it won't work without explicitly adding the http:// part.
docker run --name kibana4 -d -p 127.0.0.1:5601:5601 -e KIBANA_ES_URL=http://172.17.0.190:9200 bobrik/kibana4
I don't suppose there is a way to feed the ip of the running elasticsearch container (172.17.0.190) automatically by including this in the run.sh?
Thanks.

**Comment by bobrik** [comment]
I'm glad it worked for you, closing this issue then.

There is no way to guess where elasticsearch is running for you, so you have to set location explicitly. http part is needed too, because https is possible.
